name: Deploy Docs to Cloudflare

on:
  push:
    branches:
      - andreja/cloudflare

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wormhole-docs
        uses: actions/checkout@v3
        with:
          ref: andreja/cloudflare

      - name: Clone wormhole-mkdocs (andreja/cloudflare)
        run: |
          git clone --single-branch --branch andreja/cloudflare https://github.com/kapetan3sid/wormhole-mkdocs.git mkdocs

      - name: Copy docs content into mkdocs/docs
        run: |
          rsync -av --delete ./ mkdocs/docs

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install MkDocs + plugins
        run: |
          cd mkdocs
          pip install -r requirements.txt

      - name: Build MkDocs site
        run: |
          cd mkdocs
          mkdocs build

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        run: |
          cd mkdocs
          wrangler pages publish site --project-name=wormhole-docs --branch=andreja-cloudflare
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
