name: Deploy MkDocs to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone wormhole-mkdocs
        uses: actions/checkout@v4
        with:
          repository: kapetan3sid/wormhole-mkdocs
          path: wormhole-mkdocs

      - name: Clone wormhole-docs (this repo)
        uses: actions/checkout@v4
        with:
          path: wormhole-mkdocs/wormhole-docs

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.10

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: wormhole-mkdocs

      - name: Build MkDocs site
        run: mkdocs build
        working-directory: wormhole-mkdocs

      - name: Install Wrangler
        run: npm install -g wrangler@4

      - name: Deploy to Cloudflare Pages
        run: wrangler pages deploy ./site --project-name=wormhole-docs
        working-directory: wormhole-mkdocs
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
