name: Deploy Docs to Cloudflare

on:
  push:
    branches:
      - andreja/cloudflare

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone wormhole-mkdocs (andreja/cloudflare)
        run: |
          git clone --single-branch --branch andreja/cloudflare https://github.com/kapetan3sid/wormhole-mkdocs.git mkdocs

      - name: Clone wormhole-docs (andreja/cloudflare) into mkdocs/wormhole-docs
        run: |
          git clone --single-branch --branch andreja/cloudflare https://github.com/kapetan3sid/wormhole-docs.git mkdocs/wormhole-docs

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install MkDocs + plugins
        run: |
          cd mkdocs
          pip install -r requirements.txt

      - name: Build MkDocs site
        run: |
          cd mkdocs
          mkdocs build

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        run: |
          cd mkdocs
          wrangler pages deploy site --project-name=wormhole-docs --branch=andreja-cloudflare --commit-dirty=true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

