name: Deploy MkDocs to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wormhole-mkdocs repo
        uses: actions/checkout@v4
        with:
          repository: kapetan3sid/wormhole-mkdocs
          path: wormhole-mkdocs

      - name: Checkout wormhole-docs (this repo)
        uses: actions/checkout@v4
        with:
          path: kapetan3sid/wormhole-docs

      - name: Set up Python 3.11.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.10

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: wormhole-mkdocs

      - name: Build site with MkDocs
        run: mkdocs build
        working-directory: wormhole-mkdocs

      - name: Install Wrangler v4
        run: npm install -g wrangler@4
      
      - name: Deploy using Wrangler
        run: wrangler deploy
        working-directory: wormhole-mkdocs
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      
